/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui {
    export class LoginUI extends View {
		public pveBtn:Laya.Button;
		public pvpBtn:Laya.Button;
		public messBtn:Laya.Button;
		public logo:Laya.Panel;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Login");
        }
    }
    export class MatchUI extends View {
		public menu:Laya.Panel;
		public menuBtn:Laya.Button;
		public selectInfo:Laya.ComboBox;
		public historyBtn:Laya.Button;
		public control:Laya.Sprite;
		public hintBtn:Laya.Button;
		public defeatBtn:Laya.Button;
		public undoBtn:Laya.Button;
		public quitBtn:Laya.Button;
		public board:Laya.Image;
		public checkImg:Laya.Image;
		public resultImg:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Match");
        }
    }
}